
/* Options for Nuttx */

#undef CONFIG_ESP32_WIFI_NVS_ENABLED
#ifdef CONFIG_ESP32_WIFI_SAVE_PARAM
#define CONFIG_ESP32_WIFI_NVS_ENABLED 1
#else
#define CONFIG_ESP32_WIFI_NVS_ENABLED 0
#endif

#define CONFIG_IDF_TARGET_ESP32S2BETA 0
#define CONFIG_IDF_TARGET_ESP32S2 0
#define CONFIG_ESP32_SUPPORT_MULTIPLE_PHY_INIT_DATA_BIN 0
#define CONFIG_ESP32_WIFI_CSI_ENABLED 0
#define CONFIG_NEWLIB_NANO_FORMAT 0
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_1 0
#define CONFIG_ESP32_SPIRAM_SUPPORT 0
#define CONFIG_ESP32S2_SPIRAM_SUPPORT 0
