
/* Options for Nuttx */

#undef CONFIG_ESP32_WIFI_NVS_ENABLED
#ifdef CONFIG_ESP32C3_WIFI_SAVE_PARAM
#define CONFIG_ESP32_WIFI_NVS_ENABLED 1
#else
#define CONFIG_ESP32_WIFI_NVS_ENABLED 0
#endif

#define CONFIG_MAC_BB_PD 0
#define SOC_WIFI_HW_TSF 1
#define CONFIG_ESP32_WIFI_AMSDU_TX_ENABLED 0

#define CONFIG_ESP32_ECO3_CACHE_LOCK_FIX 0
#define CONFIG_IDF_TARGET_ESP32 0
#define CONFIG_IDF_TARGET_ESP32S2 0
#define CONFIG_IDF_TARGET_ESP32S3 0
#define CONFIG_IDF_TARGET_ESP32C2 0
#define CONFIG_ESP32_SUPPORT_MULTIPLE_PHY_INIT_DATA_BIN 0
#define CONFIG_ESP32_WIFI_CSI_ENABLED 0
#define CONFIG_NEWLIB_NANO_FORMAT 0
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_1 0
#define CONFIG_ESP32_SPIRAM_SUPPORT 0
#define CONFIG_ESP32S2_SPIRAM_SUPPORT 0
#define CONFIG_ESP32S3_SPIRAM_SUPPORT 0

#define CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE 0

#define SOC_COEX_HW_PTI 1

#define ESP_TASK_BT_CONTROLLER_STACK    0
#define ESP_TASK_BT_CONTROLLER_PRIO     0
